### ISSUE TITLE
key error in get_sample_stats

### ISSUE THREAD

**Issue by kaltinel** [KleistLab/NanoPore_dRNASeq#1]
Hi, 

I hope you are well.
I am trying to use your code to do similar analyses for my dRNA files, however I keep receiving an error which I could not get around.

I am trying to run the first notebook:
```
samples = analysis_set["main"] 

read_stats = {}
for sample in samples:
    name2qscores, name2lengths = get_summaries(summary_files[sample])
    read_stats[sample]= get_sample_stats(sample, refs[sample], name2qscores, name2lengths)

    print(sample, np.median(read_stats[sample]["acc"]), np.median(read_stats[sample]["metrics"], axis = 0))
```
Just to try, I am using only one sample, and parsing it with `read_samfile()`. However, `get_summaries()` is giving an error regarding a read, where I can see no issues with.
It is a key error, which should indicate that I dont have the 'key' but I certainly do in both `.sam,` `sequence_summary.txt` and `.fastq`.
The terminal output is:
'''
```
The number of supplementary alignments in this sample is  0
The number of sequences in this sample is  3936
  0%|                                                                                                                                                                             | 0/3936 [00:00<?, ?it/s]
Traceback (most recent call last):
    read_stats[sample]= get_sample_stats(sample, refs[sample], name2qscores, name2lengths)
  File "core.py", line 68, in get_sample_stats
    qscore, length = qscores[name], lengths[name]
KeyError: '2c6d1eab-dc1c-47c7-aae2-6e468290253d'
```
I copied the information of this read from sequence_summary.txt, and parsed it with the same code on a Jupyter notebook sheet: then the parsing is successful. Therefore I am a bit unsure of what's going on with that read.

I look forward to your help, thanks!

**Comment by kaltinel** [comment]
Hi again,

I am able to find out what was going on.
The indexing in `get_summaries() `was off as it was using `index=1` and pointing to the fast5 filename, while it was later looking for a read_name.
Therefore the solution is to change the `index` to `2` to point read_name:
```
def get_summaries(summaryfile, subsample = None):
    qscores, lengths = {},{}
    with open(summaryfile, "r") as f:
        next(f)
        for line in f:
            if subsample is not None and len(qscores) < subsample:
                items = line.strip().split()
                qscores[items[2]] = float(items[14])
                lengths[items[2]] = float(items[13])
            if subsample is None:
                items = line.strip().split()
                qscores[items[2]] = float(items[14])
                lengths[items[2]] = float(items[13])
    return qscores, lengths
```

**Comment by ChaseWLW** [comment]
Great to hear :) Interesting that there are different types of summary files...
