### ISSUE TITLE
OSError: file `sars2/sars2ivt/SARS-CoV-2.fa` not found

### ISSUE THREAD

**Issue by JannesSP** [KleistLab/NanoPore_dRNASeq#2]
Hey Liu-Wei,

just wanted to try the eval.py to compare Guppy to Dorado errors (I hope this was the correct script for that :D).
I think I installed all the necessary tools to run your code, but this error showed up:

```
python eval.py --help
Traceback (most recent call last):
  File "eval.py", line 1, in <module>
    from core_eval import *
  File "core_eval.py", line 14, in <module>
    from utils import *
  File "utils.py", line 15, in <module>
    refs["SARS2_IVT"] = pysam.Fastafile("sars2/sars2ivt/SARS-CoV-2.fa") # CTTT instead of CTTC in the paper...
  File "pysam/libcfaidx.pyx", line 121, in pysam.libcfaidx.FastaFile.__cinit__
  File "pysam/libcfaidx.pyx", line 153, in pysam.libcfaidx.FastaFile._open
OSError: file `sars2/sars2ivt/SARS-CoV-2.fa` not found
```

Kind regards,
Jannes

**Comment by ChaseWLW** [comment]
Hey @JannesSP, thanks a lot for the issue and sorry for the delay! 

I unfortunately don't have access to the server right now, and can only update the script next week. One way to get around this quickly is to comment out all the hard coded paths in `utils.py`, which should fix it :)

**Comment by ChaseWLW** [comment]
Hey @JannesSP, I was sick for a while and only got to do the changes now :) But I think you probably have it figured out already. Thanks again for the issue!
